apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-traefik-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-traefik
  ports:
    - protocol: TCP
      port: {{ .Values.traefik.service.port }}
      targetPort: {{ .Values.traefik.service.targetPort }}
