# values.yaml
webDeployment:
  replicaCount: 1
  image:
    repository: 690456518676.dkr.ecr.us-east-1.amazonaws.com/fastandtraefik
    tag: latest
    pullPolicy: IfNotPresent
  port: 8000

webService:
  port: 80

postgresStatefulSet:
  replicas: 2
  image:
    repository: postgres
    tag: 15-alpine
  port: 5432
  postgresUser: fastapi_traefik
  postgresPassword: fastapi_traefik
  postgresDatabase: fastapi_traefik
  locale: C.UTF-8

ingress:
  name: k8s-alb
  ingressClassName: alb

