apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.ingress.name }}
  labels:
    name: {{ .Release.Name }}-{{ .Values.ingress.name }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - http://final-project.devops-fairy.cloudns.biz/
    secretName: {{ .Release.Name }}-tls-secret
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-web-service
            port:
              number: {{ .Values.webService.port }}