apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
spec:
  selector:
    app: fastapi-traefik
  ports:
    - port: {{ .Values.webService.port }}
      targetPort: {{ .Values.webDeployment.port }}
