# traefik-role-binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-traefik-role-binding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-traefik-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-traefik-account
    namespace: default

