apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.fastapi.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fastapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fastapi
    spec:
      containers:
        - name: fastapi
          image: {{ .Values.fastapi.image.repository }}:{{ .Values.fastapi.image.tag }}
          ports:
            - containerPort: {{ .Values.fastapi.service.port }}
          env:
            - name: DATABASE_URL
              value: "{{ .Values.fastapi.database.databaseUrl }}"
