apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
