apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-chart.fullname" . }}
  labels:
    app: {{ include "fastapi-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fastapi-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fastapi-chart.name" . }}
    spec:
      containers:
        - name: web-service
          image: {{ .Values.webService.image.repository }}:{{ .Values.webService.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.webService.port }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.webService.databaseUrl }}
          command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "{{ .Values.webService.port }}"]

