apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fastapi-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "fastapi-chart.name" . }}
  selector:
    matchLabels:
      app: {{ include "fastapi-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fastapi-chart.name" . }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}

