apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.database.user | b64enc }}
  password: {{ .Values.database.password | b64enc }}
