apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.database.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
