apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fastapi.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fastapi.deployment.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.fastapi.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.fastapi.deployment.app }}
    spec:
      containers:
      - name: {{ .Values.fastapi.image.name }}
        image: "{{ .Values.fastapi.image.repository }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.fastapi.image.containerPort }}
        env:
          - name: DATABASE_URL
            value: postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
