apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.fastapi.ingress.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.fastapi.ingress.name }}
spec:
  rules:
    - host: {{ .Values.fastapi.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.fastapi.service.name }}
                port:
                  number: {{ .Values.fastapi.service.port }}
