name: Deploy App FastApi

on:
  workflow_run:
    workflows:
      - Python
    types:
      - completed
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Workflow Python status
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "Workflow Python was successful."
          else
            echo "Workflow Python failed."
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Get Short GitHub SHA and Save in Environment Variable
        run: echo "SHORT_GITHUB_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
  
      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: latest
        run: |
          echo "Building Docker image..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_GITHUB_SHA . 
          echo "Docker image built successfully."
      
          echo "Pushing Docker image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
          echo "Docker image pushed successfully."
  
  deploy_prod:
    name: deploy_prod
    environment: 
      name: production
      url: http://final-project.devops-fairy.cloudns.biz/
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
        
    - name: Update kube config
      run: |
        aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_DEFAULT_REGION }}
        
        # Debug: Print the content of kubeconfig file
        cat $HOME/.kube/config

        # Debug: Check kubectl version
        kubectl version --client

        # Debug: List Kubernetes nodes
        kubectl get nodes -o wide



    - name: Clone charts HELM
      run: |
        git clone https://github.com/FastAndTraefik/fastapi-docker-traefik.git

    - name: Install Charts db and Fastapi - prod
      run: |
        helm upgrade --install fastapi-db ./yaml-files/fastapi-app-chart --values=./yaml-files/fastapi-app-chart/values.yaml --namespace prod
