name: Python
on:
  - push
  - pull_request

jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on master
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.11"
      - name: Install development dependencies
        run: |
          pip install -r requirements.dev.txt

      - name: Run tests
        run: |
          pytest tests/

      - name: Run flake8
        uses: py-actions/flake8@v2
